"""Build EvermoreUI_QoL/MapData.lua: every world map overlay per uiMapID.

The game's map tables (WorldMapOverlay, WorldMapOverlayTile, UiMapXMapArt,
UiMap) are read as CSV exports from wago.tools for a client product, then
joined: overlay -> its map art -> the uiMapIDs that use that art, with the
overlay's tiles in row order (layer 0). The addon draws the ones you haven't
explored.

    python tools/mapdata/build.py                  # wow_classic_era
    python tools/mapdata/build.py --product wow_anniversary
"""
import argparse
import csv
import io
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "EvermoreUI_QoL", "MapData.lua")


def table(name, product):
    url = f"https://wago.tools/db2/{name}/csv?product={product}"
    req = urllib.request.Request(url, headers={"User-Agent": "EvermoreUI mapdata builder"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return list(csv.DictReader(io.StringIO(r.read().decode("utf-8"))))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--product", default="wow_classic_era")
    args = ap.parse_args()

    overlays = table("WorldMapOverlay", args.product)
    tiles = table("WorldMapOverlayTile", args.product)
    art = table("UiMapXMapArt", args.product)
    names = {r["ID"]: r["Name_lang"] for r in table("UiMap", args.product)}

    maps_for_art = {}
    for r in art:
        maps_for_art.setdefault(r["UiMapArtID"], []).append(r["UiMapID"])

    tiles_for = {}
    for r in tiles:
        if r["LayerIndex"] != "0":
            continue
        tiles_for.setdefault(r["WorldMapOverlayID"], []).append(
            (int(r["RowIndex"]), int(r["ColIndex"]), r["FileDataID"]))

    maps = {}
    for o in overlays:
        files = [t[2] for t in sorted(tiles_for.get(o["ID"], []))]
        if not files:
            continue
        entry = (int(o["TextureWidth"]), int(o["TextureHeight"]), int(o["OffsetX"]), int(o["OffsetY"]), files)
        for m in maps_for_art.get(o["UiMapArtID"], []):
            maps.setdefault(int(m), []).append(entry)

    lines = [
        "if EV_BLOCKED then return end",
        "-" * 80,
        "--  MapData.lua  (generated by tools/mapdata/build.py; do not edit by hand)",
        "--  Every map overlay the world map can show, explored or not, per uiMapID:",
        "--  { textureWidth, textureHeight, offsetX, offsetY, fileDataID, ... } with the",
        "--  tiles row by row. From the game's own map data (WorldMapOverlay,",
        f"--  WorldMapOverlayTile and UiMapXMapArt), product {args.product}.",
        "-" * 80,
        "local ADDON_NAME, ns = ...",
        "ns.MapOverlays = {",
    ]
    for m in sorted(maps):
        lines.append(f"    [{m}] = {{ -- {names.get(str(m), '?')}")
        for w, h, x, y, f in sorted(maps[m], key=lambda e: (e[3], e[2])):
            lines.append(f"        {{ {w}, {h}, {x}, {y}, {', '.join(f)} }},")
        lines.append("    },")
    lines.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"{len(maps)} maps, {sum(len(v) for v in maps.values())} overlays -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
